### ISSUE TITLE
Flex the Card Grid and Display fixes

### ISSUE THREAD

**Issue by PuneetSivananda** [PuneetSivananda/getajab.com#1]
CSS updates to display the cards in a responsive grid when used in desktop and single grid when used in the mobile

**Comment by PuneetSivananda** [comment]
UPdate

**Comment by skpandey885** [comment]
hey, can I fix this issue?

**Comment by PuneetSivananda** [comment]
Yes @skpandey885 Please create a PR for this issue

Please Refer the development branch let me know if you have any queries

**Comment by PuneetSivananda** [comment]
Fixed the latest Commit closing this Issue
